import React, { useEffect, useState } from 'react';
import { Activity, Building2, Camera, CheckCircle2, ClipboardList, CreditCard, Download, Edit3, KeyRound, LayoutDashboard, Lock, LogOut, Map, MapPin, Plus, RefreshCcw, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Store, Trash2, Upload, Users, UserPlus, X } from 'lucide-react';

const TOKEN_KEY = 'p4me-api-token';
const USER_KEY = 'p4me-api-user';
const statuses = ['Assigned', 'In Progress', 'Submitted', 'Verified', 'Rejected', 'Delivered', 'Exception'];
const jobTypes = ['Team Promo', 'Technician On-Site', 'Plumber / Contractor', 'Food Delivery', 'Package Delivery', 'Custom Proof Job'];
const fallbackDeliveryServices = ['Promote4.me Direct', 'Uber Eats', 'DoorDash', 'Instacart', 'Grubhub', 'Postmates', 'Walmart Spark', 'Amazon Flex', 'Roadie', 'Shipt', 'Custom Courier'];
const fallbackFieldRoles = ['Lead Tech', 'Dispatcher', 'Route Manager', 'Technician', 'Plumber', 'Electrician', 'Delivery Driver', 'Flyer Team Member', 'Promoter', 'Contractor', 'Customer Service', 'Client Viewer'];

function downloadCsv(filename, text) {
  const blob = new Blob([text], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function api(path, options = {}) {
  const token = localStorage.getItem(TOKEN_KEY);
  const headers = options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  return fetch(path, { ...options, headers: { ...headers, ...(options.headers || {}) } }).then(async (r) => {
    const text = await r.text(); const data = text ? JSON.parse(text) : {};
    if (!r.ok) throw new Error(data.error || 'Request failed'); return data;
  });
}

export default function ProductApp() {
  const [session, setSession] = useState(() => { const token = localStorage.getItem(TOKEN_KEY); const user = JSON.parse(localStorage.getItem(USER_KEY) || 'null'); return token && user ? { token, user } : null; });
  const [boot, setBoot] = useState(null); const [active, setActive] = useState('dashboard'); const [plans, setPlans] = useState({ plans: [], providers: [], mapProviders: [] }); const [notice, setNotice] = useState('');
  async function reload() { if (!localStorage.getItem(TOKEN_KEY)) return; try { setBoot(await api('/api/bootstrap')); } catch (e) { setNotice(e.message); } }
  useEffect(() => { api('/api/public/plans').then(setPlans).catch(() => {}); }, []);
  useEffect(() => { if (session) reload(); }, [session]);
  function onAuthed(data) { localStorage.setItem(TOKEN_KEY, data.token); localStorage.setItem(USER_KEY, JSON.stringify(data.user)); setSession({ token: data.token, user: data.user }); }
  function logout() { localStorage.removeItem(TOKEN_KEY); localStorage.removeItem(USER_KEY); setSession(null); setBoot(null); }
  if (!session) return <PublicSite plans={plans} onAuthed={onAuthed} />;
  if (!boot) return <div className="loading-screen"><Sparkles /> Loading workspace...</div>;
  const menu = [['dashboard','Dashboard',LayoutDashboard],['jobs','Jobs & Orders',ClipboardList],['review','Evidence Review',ShieldCheck],['map','Proof Map',Map],['team','Team',Users],['clients','Clients',Building2],['addons','Add-ons',Store],['settings','Settings',Settings]];
  const props = { boot, reload, plans, notice, setNotice };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><ShieldCheck/> Promote4.me</div><div className="mini-profile"><strong>{session.user.full_name}</strong><span>{session.user.role} · {boot.tenant?.plan}</span></div><nav>{menu.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/> Log out</button></aside><main className="workspace"><header className="topbar"><div><span className="eyebrow">{boot.tenant?.name}</span><h2>{menu.find(m=>m[0]===active)?.[1]}</h2></div><button className="secondary" onClick={reload}><RefreshCcw size={16}/> Refresh</button></header>{notice&&<div className="toast"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}{active==='dashboard'&&<Dashboard {...props}/>} {active==='jobs'&&<Jobs {...props}/>} {active==='review'&&<EvidenceReview {...props}/>} {active==='map'&&<ProofMap {...props}/>} {active==='team'&&<Team {...props}/>} {active==='clients'&&<Clients {...props}/>} {active==='addons'&&<AddOns {...props}/>} {active==='settings'&&<SettingsPanel {...props}/>}</main></div>;
}

function PublicSite({ plans, onAuthed }) { const [mode,setMode]=useState('home'); return <main className="marketing"><section className="hero-card marketing-hero"><div className="badge"><Sparkles size={18}/> Proof-of-work verification</div><h1>Verify real-world work with photo proof, GPS confidence, maps, and audit trails.</h1><p>Promote4.me helps agencies, restaurants, stores, contractors, drivers, and field teams prove work happened at the right place before rewards or invoices are approved.</p><div className="hero-actions"><button className="primary big" onClick={()=>setMode('signup')}>Start free</button><button className="secondary big" onClick={()=>setMode('login')}>Log in</button></div><div className="feature-grid"><Feature icon={Camera} title="GPS photo proof" text="Score browser GPS and image metadata against client locations."/><Feature icon={ShoppingBag} title="Store ready" text="Shopify, restaurants, WooCommerce, Uber Eats, DoorDash, Instacart, Grubhub, Spark, Flex, Roadie, Shipt, and local services."/><Feature icon={Users} title="Team ops" text="Promoters, drivers, technicians, managers, admins, clients."/></div></section>{mode==='login'&&<AuthCard action="login" onAuthed={onAuthed} onBack={()=>setMode('home')}/>} {mode==='signup'&&<AuthCard action="register" onAuthed={onAuthed} onBack={()=>setMode('home')}/>}<section className="pricing-section"><h2>Plans that make sense to buyers</h2><div className="pricing-grid">{plans.plans.map(p=><article className="price-card" key={p.id}><span>{p.name}</span><h3>{p.price}</h3><p>{p.proof}</p><ul><li>{p.jobs.toLocaleString()} jobs/mo</li><li>{p.users} users</li><li>Evidence history</li></ul><button className="primary" onClick={()=>setMode('signup')}>{p.cta}</button></article>)}</div></section></main>; }
function Feature({ icon: Icon, title, text }) { return <article><Icon/><strong>{title}</strong><p>{text}</p></article>; }
function AuthCard({ action, onAuthed, onBack }) { const [f,setF]=useState({companyName:'',fullName:'',email:'',username:action==='login'?'moveweight':'',password:'',plan:'free'}); const [error,setError]=useState(''); async function submit(e){e.preventDefault(); try{onAuthed(await api(action==='login'?'/api/auth/login':'/api/auth/register',{method:'POST',body:JSON.stringify(f)}));}catch(err){setError(err.message)}} return <form className="login-card floating-card" onSubmit={submit}><button type="button" className="text-button" onClick={onBack}>← Back</button><div className="badge"><Lock size={18}/>{action==='login'?'Log in':'Create workspace'}</div>{action==='register'&&<><input required placeholder="Company" value={f.companyName} onChange={e=>setF({...f,companyName:e.target.value})}/><input required placeholder="Your name" value={f.fullName} onChange={e=>setF({...f,fullName:e.target.value})}/><input required placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><select value={f.plan} onChange={e=>setF({...f,plan:e.target.value})}><option value="free">Free</option><option value="starter">Starter</option><option value="pro">Pro</option><option value="agency">Agency</option></select></>}<input required placeholder="Username or email" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><input required type="password" placeholder="Password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><button className="primary">{action==='login'?'Log in':'Start workspace'}</button>{error&&<div className="error-box">{error}</div>}<p className="hint">Super admin: moveweight / 123Pass!</p></form>; }

function Dashboard({ boot }) { const jobs=boot.jobs||[], evidence=jobs.flatMap(j=>j.evidence||[]), avg=evidence.length?Math.round(evidence.reduce((s,e)=>s+(e.score||0),0)/evidence.length):0; return <div className="content-grid"><section className="stat-grid"><Stat icon={ClipboardList} label="Jobs" value={jobs.length}/><Stat icon={Camera} label="Proof uploads" value={evidence.length}/><Stat icon={CheckCircle2} label="Verified" value={jobs.filter(j=>['Verified','Delivered'].includes(j.status)).length}/><Stat icon={Activity} label="Avg confidence" value={`${avg}%`}/></section><section className="panel wide"><h3>Revenue-ready pipeline</h3><div className="pipeline">{statuses.map(s=><article key={s}><strong>{s}</strong>{jobs.filter(j=>j.status===s).slice(0,5).map(j=><div className="mini-job" key={j.id}>{j.id}<span>{j.type}</span></div>)}</article>)}</div></section><section className="panel"><h3>Buyer demo script</h3><ul className="clean-list"><li>Create a client and job.</li><li>Upload proof from a phone.</li><li>Review GPS confidence and approve/reject.</li><li>Show customer proof history.</li></ul></section></div>; }
function Stat({ icon:Icon,label,value }){return <article className="stat-card"><Icon/><span>{label}</span><strong>{value}</strong></article>}

function Jobs({ boot, reload, setNotice }) { const [q,setQ]=useState(''); const [f,setF]=useState({type:'Team Promo',title:'',order_number:'',customer_name:'',customer_email:'',customer_phone:'',address:'',lat:'',lng:'',eta:'',reward_cents:'1200',instructions:'',team_id:boot.teams?.[0]?.id||'',assigned_to:boot.teamMembers?.[0]?.id||'',status:'Assigned',source:'Manual'}); const jobs=(boot.jobs||[]).filter(j=>JSON.stringify(j).toLowerCase().includes(q.toLowerCase())); async function create(e){e.preventDefault(); await api('/api/jobs',{method:'POST',body:JSON.stringify(f)}); setNotice('Job created'); reload();} async function patch(id,status){await api(`/api/jobs/${id}`,{method:'PATCH',body:JSON.stringify({status})}); reload();} return <div className="content-grid"><section className="panel wide"><div className="table-toolbar"><h3>Live jobs & orders</h3><label className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search jobs"/></label></div><DataTable headers={['Job','Customer','Proof','Status','Assigned','Action']} rows={jobs.map(j=>[<><strong>{j.id}</strong><br/><small>{j.type} · {j.order_number}</small></>,<><strong>{j.customer_name||j.title}</strong><br/><small>{j.address}</small></>,`${j.evidence?.length||0} uploads · ${bestProof(j)}`,<Status status={j.status}/>,memberName(boot,j.assigned_to),<select value={j.status} onChange={e=>patch(j.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>])}/></section><section className="panel"><h3><Plus/> Create work order</h3><form className="stack-form" onSubmit={create}><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{jobTypes.map(t=><option key={t}>{t}</option>)}</select>{['title','order_number','customer_name','customer_email','customer_phone','address','lat','lng','eta','reward_cents'].map(k=><input key={k} required={['title','customer_name','address'].includes(k)} placeholder={k.replaceAll('_',' ')} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<select value={f.assigned_to} onChange={e=>setF({...f,assigned_to:e.target.value})}>{(boot.teamMembers||[]).map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select><textarea placeholder="Instructions" value={f.instructions} onChange={e=>setF({...f,instructions:e.target.value})}/><button className="primary">Create job</button></form></section></div>; }

function EvidenceReview({ boot, reload, setNotice }) { const [selected,setSelected]=useState(boot.jobs?.[0]?.id||''); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false); const job=(boot.jobs||[]).find(j=>j.id===selected)||boot.jobs?.[0]; async function upload(e){const file=e.target.files?.[0]; if(!file||!job)return; setBusy(true); const gps=await getGps(); const exif=await getExif(file); const fd=new FormData(); fd.append('photo',file); fd.append('note',note); if(gps){fd.append('browser_lat',gps.lat); fd.append('browser_lng',gps.lng); fd.append('browser_accuracy_meters',gps.accuracy||'');} if(exif){fd.append('image_lat',exif.lat); fd.append('image_lng',exif.lng);} await api(`/api/jobs/${job.id}/evidence`,{method:'POST',body:fd}); setBusy(false); setNotice('Evidence uploaded and scored'); reload();} async function approve(status){await api(`/api/jobs/${job.id}`,{method:'PATCH',body:JSON.stringify({status})}); reload();} return <div className="content-grid"><section className="panel wide"><h3>Evidence lab</h3><select value={selected} onChange={e=>setSelected(e.target.value)}>{(boot.jobs||[]).map(j=><option key={j.id} value={j.id}>{j.id} · {j.title}</option>)}</select>{job&&<><div className="proof-summary"><Stat icon={MapPin} label="Best proof" value={bestProof(job)}/><Stat icon={Camera} label="Uploads" value={job.evidence?.length||0}/><Stat icon={CheckCircle2} label="Status" value={job.status}/></div><EvidenceCards job={job}/><div className="button-row"><button className="primary" onClick={()=>approve(job.type?.includes('Delivery')?'Delivered':'Verified')}>Approve</button><button className="secondary danger" onClick={()=>approve('Rejected')}>Reject</button></div></>}</section><section className="panel"><h3><Upload/> Upload proof</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Completion notes"/><label className="upload-box"><Camera/> {busy?'Scanning GPS...':'Select proof photo'}<input type="file" accept="image/*" capture="environment" onChange={upload}/></label></section></div>; }
function EvidenceCards({job}){if(!job.evidence?.length)return <div className="empty-proof">No proof yet.</div>;return <div className="evidence-grid">{job.evidence.map(e=><article className="evidence-card" key={e.id}>{e.file_url?<img src={e.file_url} alt={e.file_name}/>:<div className="photo-placeholder"><Camera/></div>}<div><strong>{e.file_name}</strong><p>{new Date(e.created_at).toLocaleString()}</p><Status status={e.verdict}/><p>Score {e.score}% · Distance {e.distance_feet??'unknown'} ft</p><p>Browser GPS: {coord(e.browser_lat,e.browser_lng)}</p><p>Photo GPS: {coord(e.image_lat,e.image_lng)}</p>{(e.warnings||[]).map(w=><div className="warning" key={w}>{w}</div>)}</div></article>)}</div>}

function ProofMap({ boot }) { const points=(boot.jobs||[]).filter(j=>j.lat&&j.lng); const c=points[0]||{lat:37.0842,lng:-94.5133}; return <div className="content-grid"><section className="panel wide"><h3>Open proof map</h3><iframe className="map-box" title="OpenStreetMap" src={`https://www.openstreetmap.org/export/embed.html?bbox=${Number(c.lng)-0.05}%2C${Number(c.lat)-0.05}%2C${Number(c.lng)+0.05}%2C${Number(c.lat)+0.05}&layer=mapnik&marker=${c.lat}%2C${c.lng}`}/></section><section className="panel"><h3>Locations</h3><ul className="clean-list">{points.map(j=><li key={j.id}><strong>{j.id}</strong><br/>{j.address}<br/><small>{coord(j.lat,j.lng)}</small></li>)}</ul></section></div>; }
function Team({ boot, reload, setNotice }) { const [f,setF]=useState({team_id:boot.teams?.[0]?.id||'',full_name:'',email:'',phone:'',role:'Promoter',pay_rate:'',territory:'',emergency_contact:'',notes:''}); async function add(e){e.preventDefault(); const fd=new FormData(); Object.entries(f).forEach(([k,v])=>fd.append(k,v)); const photo=e.target.photo.files[0]; if(photo)fd.append('photo',photo); await api('/api/team-members',{method:'POST',body:fd}); setNotice('Team member added'); reload();} return <div className="content-grid"><section className="panel wide"><h3>Team roster</h3><div className="card-grid">{(boot.teamMembers||[]).map(m=><article className="person-card" key={m.id}><div className="avatar">{m.photo_url?<img src={m.photo_url}/>:m.full_name?.[0]}</div><div><strong>{m.full_name}</strong><p>{m.role} · {m.territory}</p><small>{m.email} · {m.phone}</small><p>{m.notes}</p></div></article>)}</div><h3>Admins</h3><DataTable headers={['Name','Email','Role','Status']} rows={(boot.users||[]).map(u=>[u.full_name,u.email,<Status status={u.role}/>,u.status])}/></section><section className="panel"><h3><UserPlus/> Add detailed member</h3><form className="stack-form" onSubmit={add}>{['full_name','email','phone','pay_rate','territory','emergency_contact'].map(k=><input key={k} required={k==='full_name'} placeholder={k.replaceAll('_',' ')} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option>Promoter</option><option>Driver</option><option>Technician</option><option>Plumber</option><option>Manager</option></select><input name="photo" type="file" accept="image/*"/><textarea placeholder="Notes" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><button className="primary">Add member</button></form></section></div>; }
function Clients({ boot, reload, setNotice }) { const [f,setF]=useState({name:'',email:'',phone:'',address:'',lat:'',lng:'',notes:''}); async function add(e){e.preventDefault(); await api('/api/clients',{method:'POST',body:JSON.stringify(f)}); setNotice('Client created'); reload();} return <div className="content-grid"><section className="panel wide"><h3>Client CRM</h3><div className="card-grid">{(boot.clients||[]).map(c=><article className="client-card" key={c.id}><strong>{c.name}</strong><p>{c.address}</p><small>{c.email} · {c.phone}</small><p>{c.notes}</p></article>)}</div></section><section className="panel"><h3><Building2/> Add client</h3><form className="stack-form" onSubmit={add}>{Object.keys(f).filter(k=>k!=='notes').map(k=><input key={k} required={k==='name'} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>) }<textarea placeholder="Rules, notes, requirements" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><button className="primary">Save client</button></form></section></div>; }
function AddOns({ plans, setNotice }) { async function checkout(provider,plan){const d=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({provider,plan})}); setNotice(d.message);} return <div className="content-grid"><section className="panel wide"><h3>Installable add-ons</h3><div className="integration-grid"><Integration icon={ShoppingBag} title="Shopify stores/restaurants" text="Order-to-job webhooks and customer tracking path."/><Integration icon={Store} title="WooCommerce" text="Plugin settings, order import, tracking links."/><Integration icon={Map} title="Maps" text="OpenStreetMap plus optional premium maps."/><Integration icon={CreditCard} title="Billing" text="Checkout records are wired for live payment integrations."/></div></section><section className="panel"><h3>Upgrade tests</h3>{plans.plans.map(p=><div className="checkout-row" key={p.id}><strong>{p.name}</strong><span>{p.price}</span><button className="primary" onClick={()=>checkout('stripe',p.id)}>Checkout</button></div>)}</section></div>; }
function Integration({icon:Icon,title,text}){return <article className="integration-card"><Icon/><strong>{title}</strong><p>{text}</p></article>}
function SettingsPanel({ boot, reload, setNotice }) { const [f,setF]=useState({name:boot.tenant.name,plan:boot.tenant.plan,google_maps_api_key:boot.tenant.google_maps_api_key||'',accuracy_radius_feet:boot.tenant.accuracy_radius_feet||350,require_gps_for_rewards:!!boot.tenant.require_gps_for_rewards,map_provider:boot.tenant.map_provider||'openstreetmap',billing_email:boot.tenant.billing_email||''}); async function save(e){e.preventDefault(); await api('/api/settings',{method:'PATCH',body:JSON.stringify(f)}); setNotice('Settings saved'); reload();} async function cleanup(){const d=await api('/api/admin/cleanup-inactive',{method:'POST',body:'{}'}); setNotice(d.message)} return <div className="content-grid"><section className="panel form-panel"><h3><Settings/> Company settings</h3><form className="stack-form" onSubmit={save}><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.plan} onChange={e=>setF({...f,plan:e.target.value})}>{['free','starter','pro','agency','super'].map(x=><option key={x}>{x}</option>)}</select><select value={f.map_provider} onChange={e=>setF({...f,map_provider:e.target.value})}>{(boot.mapProviders||[]).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select><input placeholder="Map API key" value={f.google_maps_api_key} onChange={e=>setF({...f,google_maps_api_key:e.target.value})}/><input type="number" value={f.accuracy_radius_feet} onChange={e=>setF({...f,accuracy_radius_feet:e.target.value})}/><input placeholder="Billing email" value={f.billing_email} onChange={e=>setF({...f,billing_email:e.target.value})}/><label className="check-line"><input type="checkbox" checked={f.require_gps_for_rewards} onChange={e=>setF({...f,require_gps_for_rewards:e.target.checked})}/> Require GPS for reward auto-approval</label><button className="primary"><KeyRound/> Save settings</button></form></section><section className="panel"><h3>Lifecycle</h3><ul className="clean-list"><li>Status: {boot.tenant.status}</li><li>Last active: {boot.tenant.last_active_at||'now'}</li><li>Free inactive accounts: 1 year plus grace period.</li></ul><button className="secondary danger" onClick={cleanup}>Run inactive cleanup</button></section></div>; }

function DataTable({headers, rows}){return <div className="responsive-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Status({status}){return <span className={`status ${String(status||'').toLowerCase().replaceAll(' ','-').replaceAll('/','-')}`}>{status}</span>}
function bestProof(j){const e=(j.evidence||[])[0]; return e ? `${e.score}% ${e.verdict}` : 'No proof'}
function memberName(boot,id){return (boot.teamMembers||[]).find(m=>m.id===id)?.full_name || 'Unassigned'}
function coord(a,b){return a&&b ? `${Number(a).toFixed(5)}, ${Number(b).toFixed(5)}` : 'missing'}
function getGps(){return new Promise(res=>{if(!navigator.geolocation)return res(null); navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>res(null),{enableHighAccuracy:true,timeout:10000,maximumAge:0})})}
async function getExif(file){try{const exifr=await import('exifr'); const g=await exifr.gps(file); return g?.latitude&&g?.longitude?{lat:g.latitude,lng:g.longitude}:null}catch{return null}}
